name = "BlackHolesDocs"
uuid = "5b8a3b30-3f5b-4d83-9f2e-0f2b8ebc2a41"   # any UUIDv4 is fine
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"
Documenter = "1"
